services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/django/Dockerfile
    container_name: backend
    command: >
      sh -c "
        python manage.py migrate &&
        python3 manage.py collectstatic --noinput &&
        gunicorn --bind 0.0.0.0:8000 core.wsgi:application
      "
    volumes:
      - ./core:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - '8000:8000'
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    env_file:
      - ./envs/.env.prod

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/prod/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  static_volume:
  media_volume: